steps:
  # Compilación con Maven usando JDK 21
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']

  # Construcción de la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west2-docker.pkg.dev/quinielator/desmxsoft-qntr/qntr-jb-cierrequiniela:$COMMIT_SHA', '.']

images:
  - 'us-west2-docker.pkg.dev/quinielator/desmxsoft-qntr/qntr-jb-cierrequiniela:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY